# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ feature/pipeline-setup ]
  pull_request:
    branches: [ feature/pipeline-setup ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Install PyOpenSSL
    - name: Install PyOpenSSL and set env var
      env:
        CLOUDSDK_PYTHON_SITEPACKAGES: "1"
      run: pip install pyopenssl

    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '286.0.0'
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.STAGING_GCP_PROJECT_ID }}
        export_default_credentials: true

    # Check if gcloud is good to go
    - run: gcloud info

    # form-submissions
    - run: gcloud pubsub topics describe form-submissions || gcloud pubsub topics create form-submissions
